[package]
name = "audio-processor"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
console_log = "1.0.0"
hound = "3.5.1"
log = "0.4.22"
pitch_shift = "1.0.0"
wasm-bindgen = "0.2.93"
